In [1]:
import torch

print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA Version:", torch.version.cuda)
    print("GPU Count:", torch.cuda.device_count())

CUDA Available: True
GPU: Tesla T4
CUDA Version: 12.8
GPU Count: 1


In [3]:
import torch
import torch.nn as nn

In [27]:
# inputs 
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])


In [33]:
neuron = nn.Linear(in_features=3, out_features=1)

In [34]:
output = neuron(inputs)

In [35]:
output

tensor([1.0805], grad_fn=<ViewBackward0>)

In [36]:
# verify 
neuron.weight @ inputs + neuron.bias

tensor([1.0805], grad_fn=<AddBackward0>)

In [37]:
neuron.bias

Parameter containing:
tensor([0.5090], requires_grad=True)